### ISSUE TITLE
OXPath script is contiuously re-run once it is finished

### ISSUE THREAD

**Issue by neumannm** [irgroup/oxpath_docker#6]
In the current setting, the wrapper script always checks if an OXPath script in the input directory is currently being processed. This makes sense to check for new wrapper scripts and to prevent the same script being processed multiple times at once.

Unfortunately, this setting also causes one single wrapper script to be processed over and over again. This is undesirable behaviour and should be fixed. A script placed in the input folder should only be processed once, and every additional processing should be initiated by the user.

**Comment by whyrewehere** [comment]
Added a new "processed" folder for processed files. If a script should run again, users can re-add it to the input folder.
